### ISSUE TITLE
Script thinks I'm using Windows?

### ISSUE THREAD

**Issue by jwhips** [danielcshn/dude-install.sh#1]
In the Morning!  Thank you for the script.  
Here is what I'm doing.

I am using LXC Debian 11 container on Proxmox.

- instructions worked for installing git, git clone and chmod.
- Ran the dependency checker and was able to see I had to install a few dependencies. The check dependencies check then passed.
- When running 2 - failed with a wine32 error. installed wine.

The problems:
When running the installed it prompts for version. I entered 7.5.
It hangs for ~3-5 minutes, then starts throwing errors.

Errors are below. It looks to think I'm using Windoze?

Waiting for Wine to initialize...0009:err:module:__wine_process_init L"C:\\windows\\system32\\dude-install-7.5.exe" not found
Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)
Failed creating new xdo instance
Waiting for Wine to initialize...Error: Can't open display: (null)

**Comment by danielcshn** [comment]
Hi, this integration does not support containers.

The error indicates that it does not detect a screen or display, for this reason it does not open the installer.

**Comment by jwhips** [comment]
Feel a bit silly with the question as it is using WINE ... 

I will try this on a Debian 11 VM.  

Thanks in advance for the script.
